# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Slumber Pooch"
client_id = "f45a69a2e6e434f601eaece898e38cf4"
application_url = "https://entered-underlying-missed-produced.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://entered-underlying-missed-produced.trycloudflare.com/auth/callback",
  "https://entered-underlying-missed-produced.trycloudflare.com/auth/shopify/callback",
  "https://entered-underlying-missed-produced.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "abdulexamplestore.myshopify.com"
